#include "buttons.h"
#include "stm32f407xx.h"

uint16_t bound_timer;

void Buttons_init(void) {
  RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOEEN;

  RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
  SYSCFG->EXTICR[2] |= SYSCFG_EXTICR3_EXTI10_PE | SYSCFG_EXTICR3_EXTI11_PE;
  SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI12_PE;

  __enable_irq();

  // pending reset
  EXTI->PR |= EXTI_PR_PR10 | EXTI_PR_PR11 | EXTI_PR_PR12;
  
  EXTI->FTSR |= EXTI_FTSR_TR10 | EXTI_PR_PR11 | EXTI_PR_PR12;
  EXTI->IMR |= EXTI_IMR_IM10 | EXTI_IMR_IM11 | EXTI_IMR_IM12;
  NVIC_EnableIRQ(EXTI15_10_IRQn);

  // E10-E12 input mode
  GPIOE->MODER &= ~(GPIO_MODER_MODE10 | GPIO_MODER_MODE11 | GPIO_MODER_MODE12);
}

void LED_init(void) {
  RCC -> AHB1ENR |= RCC_AHB1ENR_GPIOEEN;
  // E13-E15 output mode
  GPIOE->MODER &= ~(GPIO_MODER_MODER13_Msk | GPIO_MODER_MODER14_Msk | GPIO_MODER_MODER15_Msk);
  GPIOE->MODER |= (0b01 << GPIO_MODER_MODE13_Pos) | (0b01 << GPIO_MODER_MODE14_Pos) | (0b01 << GPIO_MODER_MODE15_Pos);
  GPIOE->BSRR |= GPIO_BSRR_BS13 | GPIO_BSRR_BS14 | GPIO_BSRR_BS15;
}