#include "gpio.h"

void GPIO_Init(void){

  RCC->AHB1ENR|=RCC_AHB1ENR_GPIOEEN;

  GPIOE->MODER|=GPIO_MODER_MODE13_0;
  GPIOE->MODER|=GPIO_MODER_MODE14_0;
  GPIOE->MODER|=GPIO_MODER_MODE15_0;

  GPIOE->PUPDR|=GPIO_PUPDR_PUPD10_0;
  GPIOE->PUPDR|=GPIO_PUPDR_PUPD11_0;
  GPIOE->PUPDR|=GPIO_PUPDR_PUPD12_0; 
   GPIOE->MODER |= GPIO_MODER_MODE2_0; // PE2 output mode
// Настройка пина PE2 в режим открытого стока (open-drain)
  GPIOE->OTYPER |= GPIO_OTYPER_OT2;   // PE2 output open-drain
}


